<a href="https://colab.research.google.com/github/Sarthak-404/Mobiqliq_fantasy_pred/blob/main/Automation_Head_On_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

def clean_data_team_1(url):
    # Load the data from the URL
    tables = pd.read_html(url)

    # Function to clean batting data
    def clean_batting(df):
        # Drop unnecessary columns
        df = df.drop(['Unnamed: 8', 'Unnamed: 9', 'Unnamed: 1', 'M'], axis=1)

        # Drop rows with NaN in the 'R' column as those rows are irrelevant (like Extras, Total)
        df = df.dropna(subset=['R'])

        # Drop rows where 'BATTING' contains 'Extras', 'TOTAL'
        df = df[~df['BATTING'].isin(['Extras', 'TOTAL'])]

        # Rename the 'BATTING' column to 'PLAYERS'
        df = df.rename(columns={'BATTING': 'PLAYERS'})

        # Reset the index to start from 0
        df = df.reset_index(drop=True)

        # Define a function to check if all values in a row are the same
        def all_columns_same(row):
            return all(row == row.iloc[0])

        # Apply this function along the rows and filter out those rows where the condition is True
        df = df[~df.apply(all_columns_same, axis=1)]

        # Reset the index if needed
        df = df.reset_index(drop=True)

        return df

    # Function to clean bowling data
    def clean_bowling(df):
        # Drop rows where 'W' column contains non-numeric data (i.e., drop commentary rows)
        df = df[pd.to_numeric(df['W'], errors='coerce').notna()]

        # Optionally, convert all numeric columns to their proper types
        numeric_columns = ['O', 'M', 'R', 'W', 'ECON', '0s', '4s', '6s', 'WD', 'NB']
        df[numeric_columns] = df[numeric_columns].apply(pd.to_numeric, errors='coerce')

        # Reset index after filtering
        df = df.reset_index(drop=True)

        return df

    # Clean batting data (assuming tables[0] is the batting table)
    cleaned_batting = clean_batting(tables[0])

    # Clean bowling data (assuming tables[3] is the bowling table)
    cleaned_bowling = clean_bowling(tables[3].rename(columns={'BOWLING': 'PLAYERS'}))

    # Concatenate the cleaned batting and bowling data
    combined_df = pd.concat([cleaned_batting, cleaned_bowling], axis=0, ignore_index=True)

    return combined_df

# Usage
url = 'https://www.espncricinfo.com/series/caribbean-premier-league-2023-1369538/trinbago-knight-riders-vs-guyana-amazon-warriors-final-1369591/full-scorecard'
team_1 = clean_data_team_1(url)

# Display the resulting DataFrame
team_1

<ipython-input-1-8bc9570f4da9>:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[numeric_columns] = df[numeric_columns].apply(pd.to_numeric, errors='coerce')

,PLAYERS,R,B,4s,6s,SR,O,M,W,ECON,0s,WD,NB
0,Chadwick Walton,10,11,2,0,90.90,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Mark Deyal,16,9,2,1,177.77,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Nicholas Pooran †,1,5,0,0,20.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Keacy Carty,38,45,2,1,84.44,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Kieron Pollard (c),0,4,0,0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Akeal Hosein,1,2,0,0,50.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Andre Russell,3,5,0,0,60.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Dwayne Bravo,8,18,1,0,44.44,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Sunil Narine,1,4,0,0,25.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Ali Khan,1,2,0,0,50.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Waqar Salamkheil,1,4,0,0,25.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Akeal Hosein,21,NaN,2,0,NaN,4.0,0.0,1.0,5.25,11.0,0.0,0.0
12,Andre Russell,12,NaN,2,0,NaN,1.0,0.0,0.0,12.00,3.0,2.0,0.0
13,Sunil Narine,10,NaN,0,0,NaN,4.0,0.0,0.0,2.50,15.0,0.0,0.0
14,Waqar Salamkheil,26,NaN,0,3,NaN,3.0,0.0,0.0,8.66,8.0,0.0,0.0
15,Ali Khan,28,NaN,2,2,NaN,2.0,0.0,0.0,14.00,2.0,0.0,0.0

In [2]:
import pandas as pd

def clean_data_team_2(url):
    # Load the data from the URL
    tables = pd.read_html(url)

    # Function to clean batting data
    def clean_batting(df):
        # Drop unnecessary columns
        df = df.drop(['Unnamed: 8', 'Unnamed: 9', 'Unnamed: 1', 'M'], axis=1)

        # Drop rows with NaN in the 'R' column as those rows are irrelevant (like Extras, Total)
        df = df.dropna(subset=['R'])

        # Drop rows where 'BATTING' contains 'Extras', 'TOTAL'
        df = df[~df['BATTING'].isin(['Extras', 'TOTAL'])]

        # Rename the 'BATTING' column to 'PLAYERS'
        df = df.rename(columns={'BATTING': 'PLAYERS'})

        # Reset the index to start from 0
        df = df.reset_index(drop=True)

        # Define a function to check if all values in a row are the same
        def all_columns_same(row):
            return all(row == row.iloc[0])

        # Apply this function along the rows and filter out those rows where the condition is True
        df = df[~df.apply(all_columns_same, axis=1)]

        # Reset the index if needed
        df = df.reset_index(drop=True)

        return df

    # Function to clean bowling data
    def clean_bowling(df):
        # Drop rows where 'W' column contains non-numeric data (i.e., drop commentary rows)
        df = df[pd.to_numeric(df['W'], errors='coerce').notna()]

        # Optionally, convert all numeric columns to their proper types
        numeric_columns = ['O', 'M', 'R', 'W', 'ECON', '0s', '4s', '6s', 'WD', 'NB']
        df[numeric_columns] = df[numeric_columns].apply(pd.to_numeric, errors='coerce')

        # Reset index after filtering
        df = df.reset_index(drop=True)

        return df

    # Clean batting data (assuming tables[0] is the batting table)
    cleaned_batting = clean_batting(tables[2])

    # Clean bowling data (assuming tables[3] is the bowling table)
    cleaned_bowling = clean_bowling(tables[1].rename(columns={'BOWLING': 'PLAYERS'}))

    # Concatenate the cleaned batting and bowling data
    combined_df = pd.concat([cleaned_batting, cleaned_bowling], axis=0, ignore_index=True)

    return combined_df

# Usage
url = 'https://www.espncricinfo.com/series/caribbean-premier-league-2023-1369538/trinbago-knight-riders-vs-guyana-amazon-warriors-final-1369591/full-scorecard'
team_2 = clean_data_team_2(url)

# Display the resulting DataFrame
team_2

<ipython-input-2-1490aea83137>:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[numeric_columns] = df[numeric_columns].apply(pd.to_numeric, errors='coerce')

,PLAYERS,R,B,4s,6s,SR,O,M,W,ECON,0s,WD,NB
0,Saim Ayub,52,41,2,5,126.82,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Keemo Paul,11,11,2,0,100.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Shai Hope,32,32,2,0,100.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Dwaine Pretorius,26,NaN,2,1,NaN,4.0,0.0,4.0,6.50,13.0,2.0,0.0
4,Romario Shepherd,17,NaN,3,0,NaN,3.0,0.0,1.0,5.66,10.0,0.0,0.0
5,Ronsford Beaton,30,NaN,2,1,NaN,3.1,0.0,1.0,9.47,8.0,5.0,0.0
6,Gudakesh Motie,7,NaN,0,0,NaN,4.0,1.0,2.0,1.75,17.0,0.0,0.0
7,Imran Tahir,8,NaN,0,0,NaN,4.0,0.0,2.0,2.00,18.0,1.0,0.0

# **Combined Code**

In [3]:
import pandas as pd

class CricketDataCleaner:
    def __init__(self, url):
        self.url = url
        self.tables = pd.read_html(url)

    def clean_batting(self, df):
        df = df.drop(['Unnamed: 8', 'Unnamed: 9', 'Unnamed: 1', 'M'], axis=1)
        df = df.dropna(subset=['R'])
        df = df[~df['BATTING'].isin(['Extras', 'TOTAL'])]
        df = df.rename(columns={'BATTING': 'PLAYERS'})
        df['PLAYERS'] = df['PLAYERS'].str.replace(r'(\s*\(c\))|(\s*†)', '', regex=True)
        df = df.reset_index(drop=True)

        def all_columns_same(row):
            return all(row == row.iloc[0])

        df = df[~df.apply(all_columns_same, axis=1)]
        df = df.reset_index(drop=True)

        return df

    def clean_bowling(self, df):
        df = df.rename(columns={'BOWLING': 'PLAYERS'})
        df['PLAYERS'] = df['PLAYERS'].str.replace(r'(\s*\(c\))|(\s*†)', '', regex=True)
        df = df[pd.to_numeric(df['W'], errors='coerce').notna()]
        numeric_columns = ['O', 'M', 'R', 'W', 'ECON', '0s', '4s', '6s', 'WD', 'NB']
        df[numeric_columns] = df[numeric_columns].apply(pd.to_numeric, errors='coerce')
        df = df.reset_index(drop=True)

        return df

    def clean_team_data(self, batting_index, bowling_index):
        cleaned_batting = self.clean_batting(self.tables[batting_index])
        cleaned_bowling = self.clean_bowling(self.tables[bowling_index])
        combined_df = pd.concat([cleaned_batting, cleaned_bowling], axis=0, ignore_index=True)

        return combined_df

In [4]:
url = 'https://www.espncricinfo.com/series/caribbean-premier-league-2023-1369538/trinbago-knight-riders-vs-guyana-amazon-warriors-final-1369591/full-scorecard'
cleaner = CricketDataCleaner(url)

team_1_data = cleaner.clean_team_data(batting_index=0, bowling_index=3)
team_2_data = cleaner.clean_team_data(batting_index=2, bowling_index=1)

In [5]:
team_1_data

,PLAYERS,R,B,4s,6s,SR,O,M,W,ECON,0s,WD,NB
0,Chadwick Walton,10,11,2,0,90.90,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Mark Deyal,16,9,2,1,177.77,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Nicholas Pooran,1,5,0,0,20.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Keacy Carty,38,45,2,1,84.44,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Kieron Pollard,0,4,0,0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Akeal Hosein,1,2,0,0,50.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Andre Russell,3,5,0,0,60.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Dwayne Bravo,8,18,1,0,44.44,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Sunil Narine,1,4,0,0,25.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Ali Khan,1,2,0,0,50.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Waqar Salamkheil,1,4,0,0,25.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Akeal Hosein,21,NaN,2,0,NaN,4.0,0.0,1.0,5.25,11.0,0.0,0.0
12,Andre Russell,12,NaN,2,0,NaN,1.0,0.0,0.0,12.00,3.0,2.0,0.0
13,Sunil Narine,10,NaN,0,0,NaN,4.0,0.0,0.0,2.50,15.0,0.0,0.0
14,Waqar Salamkheil,26,NaN,0,3,NaN,3.0,0.0,0.0,8.66,8.0,0.0,0.0
15,Ali Khan,28,NaN,2,2,NaN,2.0,0.0,0.0,14.00,2.0,0.0,0.0

In [6]:
team_2_data

,PLAYERS,R,B,4s,6s,SR,O,M,W,ECON,0s,WD,NB
0,Saim Ayub,52,41,2,5,126.82,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Keemo Paul,11,11,2,0,100.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Shai Hope,32,32,2,0,100.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"Did not bat: Odean Smith, Shimron Hetmyer, Aza...","Did not bat: Odean Smith, Shimron Hetmyer, Aza...","Did not bat: Odean Smith, Shimron Hetmyer, Aza...","Did not bat: Odean Smith, Shimron Hetmyer, Aza...","Did not bat: Odean Smith, Shimron Hetmyer, Aza...","Did not bat: Odean Smith, Shimron Hetmyer, Aza...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Dwaine Pretorius,26,NaN,2,1,NaN,4.0,0.0,4.0,6.50,13.0,2.0,0.0
5,Romario Shepherd,17,NaN,3,0,NaN,3.0,0.0,1.0,5.66,10.0,0.0,0.0
6,Ronsford Beaton,30,NaN,2,1,NaN,3.1,0.0,1.0,9.47,8.0,5.0,0.0
7,Gudakesh Motie,7,NaN,0,0,NaN,4.0,1.0,2.0,1.75,17.0,0.0,0.0
8,Imran Tahir,8,NaN,0,0,NaN,4.0,0.0,2.0,2.00,18.0,1.0,0.0

# **Primitive Approach (Working with small issues)**

In [7]:
urls = [
    'https://www.espncricinfo.com/series/caribbean-premier-league-2023-1369538/trinbago-knight-riders-vs-guyana-amazon-warriors-final-1369591/full-scorecard',
    'https://www.espncricinfo.com/series/caribbean-premier-league-2023-1369538/guyana-amazon-warriors-vs-jamaica-tallawahs-qualifier-2-1369590/full-scorecard',
    'https://www.espncricinfo.com/series/caribbean-premier-league-2023-1369538/guyana-amazon-warriors-vs-trinbago-knight-riders-qualifier-1-1369589/full-scorecard',
    'https://www.espncricinfo.com/series/caribbean-premier-league-2023-1369538/st-lucia-kings-vs-jamaica-tallawahs-eliminator-1369588/full-scorecard',
    'https://www.espncricinfo.com/series/caribbean-premier-league-2023-1369538/barbados-royals-vs-guyana-amazon-warriors-30th-match-1369587/full-scorecard',
    'https://www.espncricinfo.com/series/caribbean-premier-league-2023-1369538/jamaica-tallawahs-vs-st-lucia-kings-29th-match-1369586/full-scorecard',
    'https://www.espncricinfo.com/series/caribbean-premier-league-2023-1369538/guyana-amazon-warriors-vs-trinbago-knight-riders-28th-match-1369585/full-scorecard',
    'https://www.espncricinfo.com/series/caribbean-premier-league-2023-1369538/jamaica-tallawahs-vs-st-kitts-and-nevis-patriots-27th-match-1369584/full-scorecard',
    'https://www.espncricinfo.com/series/caribbean-premier-league-2023-1369538/guyana-amazon-warriors-vs-st-lucia-kings-26th-match-1369583/full-scorecard',
    'https://www.espncricinfo.com/series/caribbean-premier-league-2023-1369538/guyana-amazon-warriors-vs-jamaica-tallawahs-25th-match-1369582/full-scorecard',
    'https://www.espncricinfo.com/series/caribbean-premier-league-2023-1369538/st-lucia-kings-vs-trinbago-knight-riders-24th-match-1369581/full-scorecard',
    'https://www.espncricinfo.com/series/caribbean-premier-league-2023-1369538/barbados-royals-vs-guyana-amazon-warriors-23rd-match-1369580/full-scorecard',
    'https://www.espncricinfo.com/series/caribbean-premier-league-2023-1369538/jamaica-tallawahs-vs-trinbago-knight-riders-22nd-match-1369579/full-scorecard',
    'https://www.espncricinfo.com/series/caribbean-premier-league-2023-1369538/st-lucia-kings-vs-st-kitts-and-nevis-patriots-21st-match-1369578/full-scorecard',
    'https://www.espncricinfo.com/series/caribbean-premier-league-2023-1369538/barbados-royals-vs-trinbago-knight-riders-20th-match-1369577/full-scorecard',
    'https://www.espncricinfo.com/series/caribbean-premier-league-2023-1369538/guyana-amazon-warriors-vs-trinbago-knight-riders-19th-match-1369576/full-scorecard',
    'https://www.espncricinfo.com/series/caribbean-premier-league-2023-1369538/barbados-royals-vs-st-kitts-and-nevis-patriots-18th-match-1369575/full-scorecard',
    'https://www.espncricinfo.com/series/caribbean-premier-league-2023-1369538/jamaica-tallawahs-vs-trinbago-knight-riders-17th-match-1369574/full-scorecard',
    'https://www.espncricinfo.com/series/caribbean-premier-league-2023-1369538/barbados-royals-vs-st-lucia-kings-16th-match-1369573/full-scorecard',
    'https://www.espncricinfo.com/series/caribbean-premier-league-2023-1369538/guyana-amazon-warriors-vs-st-kitts-and-nevis-patriots-15th-match-1369572/full-scorecard',
    'https://www.espncricinfo.com/series/caribbean-premier-league-2023-1369538/barbados-royals-vs-jamaica-tallawahs-14th-match-1369571/full-scorecard',
    'https://www.espncricinfo.com/series/caribbean-premier-league-2023-1369538/barbados-royals-vs-trinbago-knight-riders-13th-match-1369570/full-scorecard',
    'https://www.espncricinfo.com/series/caribbean-premier-league-2023-1369538/st-kitts-and-nevis-patriots-vs-trinbago-knight-riders-12th-match-1369569/full-scorecard',
    'https://www.espncricinfo.com/series/caribbean-premier-league-2023-1369538/guyana-amazon-warriors-vs-jamaica-tallawahs-11th-match-1369568/full-scorecard',
    'https://www.espncricinfo.com/series/caribbean-premier-league-2023-1369538/barbados-royals-vs-st-kitts-and-nevis-patriots-10th-match-1369567/full-scorecard',
    'https://www.espncricinfo.com/series/caribbean-premier-league-2023-1369538/st-lucia-kings-vs-trinbago-knight-riders-9th-match-1369566/full-scorecard',
]

In [8]:
# Extract match names from URLs
match_names = [url.split('/')[-2] for url in urls]

# Print the match names
print(match_names)

['trinbago-knight-riders-vs-guyana-amazon-warriors-final-1369591', 'guyana-amazon-warriors-vs-jamaica-tallawahs-qualifier-2-1369590', 'guyana-amazon-warriors-vs-trinbago-knight-riders-qualifier-1-1369589', 'st-lucia-kings-vs-jamaica-tallawahs-eliminator-1369588', 'barbados-royals-vs-guyana-amazon-warriors-30th-match-1369587', 'jamaica-tallawahs-vs-st-lucia-kings-29th-match-1369586', 'guyana-amazon-warriors-vs-trinbago-knight-riders-28th-match-1369585', 'jamaica-tallawahs-vs-st-kitts-and-nevis-patriots-27th-match-1369584', 'guyana-amazon-warriors-vs-st-lucia-kings-26th-match-1369583', 'guyana-amazon-warriors-vs-jamaica-tallawahs-25th-match-1369582', 'st-lucia-kings-vs-trinbago-knight-riders-24th-match-1369581', 'barbados-royals-vs-guyana-amazon-warriors-23rd-match-1369580', 'jamaica-tallawahs-vs-trinbago-knight-riders-22nd-match-1369579', 'st-lucia-kings-vs-st-kitts-and-nevis-patriots-21st-match-1369578', 'barbados-royals-vs-trinbago-knight-riders-20th-match-1369577', 'guyana-amazon-warriors-vs-trinbago-knight-riders-19th-match-1369576', 'barbados-royals-vs-st-kitts-and-nevis-patriots-18th-match-1369575', 'jamaica-tallawahs-vs-trinbago-knight-riders-17th-match-1369574', 'barbados-royals-vs-st-lucia-kings-16th-match-1369573', 'guyana-amazon-warriors-vs-st-kitts-and-nevis-patriots-15th-match-1369572', 'barbados-royals-vs-jamaica-tallawahs-14th-match-1369571', 'barbados-royals-vs-trinbago-knight-riders-13th-match-1369570', 'st-kitts-and-nevis-patriots-vs-trinbago-knight-riders-12th-match-1369569', 'guyana-amazon-warriors-vs-jamaica-tallawahs-11th-match-1369568', 'barbados-royals-vs-st-kitts-and-nevis-patriots-10th-match-1369567', 'st-lucia-kings-vs-trinbago-knight-riders-9th-match-1369566']

In [9]:
for i in range(len(urls)):
  cleaner = CricketDataCleaner(urls[i])
  team_1_data = cleaner.clean_team_data(batting_index=0, bowling_index=3)
  team_2_data = cleaner.clean_team_data(batting_index=2, bowling_index=1)
  df = pd.concat([team_1_data, team_2_data], axis=0, ignore_index=True)
  df.to_csv(f'{match_names[i]}.csv', index=False)